### ISSUE TITLE
Does v4 still require key encapsulation for client callers? What about v5?

### ISSUE THREAD

**Issue by jonbartels** [Appriss-Operations/pmp_gateway_docs#2]
I am comparing the newer documentation published by this project at http://appriss-operations.github.io/pmp_gateway_docs/v4/ against older documentation handed off to me from a peer. The older documentation is a ZIP file and is labeled as being for PMP Interconnect v4. The file located within this ZIP at technical/security/encryption/README.txt and describes a process of key encapsulation. This is referenced again at technical/api/v4/encryption.html. The older documentation does rather a good job describing how to implement this encryption scheme. 

The newer documentation does not reference this encapsulation scheme that I can find. Am I overlooking something?

Does v4 still require the key encapsulation scheme for client calls to the PMP Gateway?

Does v5 have any similar requirements?

**Comment by nslocum** [comment]
The new online documentation doesn't include the encryption stuff you mentioned. What type of implementation are you working on? The more you can tell us about how you're using the API, the better we can assist.

**Comment by jonbartels** [comment]
Nothing too complicated. Just an integration with a provider facing piece of software to call the PMP API as a client. I was involved with a similar project at a prior employer and that implementation was challenging because of the encryption scheme. It worked out easily enough but it certainly required more time beyond basic SSL.

So that I am 100% clear, the new documentation does not include the encryption information. Does that mean that the API still needs it?

**Comment by nslocum** [comment]
You can make API requests with HTTPS using a username and password.
Here's an example: http://appriss-operations.github.io/pmp_gateway_docs/v5/#patient-request-minimal

The curl examples should work for you. Just replace the username and password with your credentials.

**Comment by jonbartels** [comment]
That is excellent news! Thank you.
